### ISSUE TITLE
Кто такие "Gl"?

### ISSUE THREAD

**Issue by ukloung** [PlutoSolutions/BozeUpdate#6]
Увидел упоминания в некоторых вопросах. Хотелось бы знать, что это)

**Comment by cattyngmd** [comment]
Peter, otherwise known as "GL_DONT_CARE" is a member of the konas / boze development team. unlike his counterparts he is very odd and very weird.

**Comment by AllahLeaksHvH** [comment]
Peter, otherwise known as "GL_DONT_CARE" is a member of the konas / boze development team. unlike his counterparts he is very odd and very weird.

**Comment by ukloung** [comment]
> Peter, otherwise known as "GL_DONT_CARE" is a member of the konas / boze development team. unlike his counterparts he is very odd and very weird.

The
